#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle    T_n = n(n+1)/2     1, 3,  6, 10, 15, ...
Pentagonal  P_n = n(3n−1)/2    1, 5, 12, 22, 35, ...
Hexagonal   H_n = n(2n−1)      1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

import sys

def triangle():
  """
  T_n = n(n+1)/2
  """
  n = 1
  while True:
    yield n * (n+1) / 2
    n += 1


def pentagonal():
  """
  P_n = n(3n-1)/2
  """
  n = 1
  while True:
    yield n * (3*n-1) / 2
    n += 1


def hexagonal():
  """
  H_n = n(2n-1)
  """
  n = 1
  while True:
    yield n * (2*n-1)
    n += 1


def answer(n):
  t_gen, p_gen, h_gen = triangle(), pentagonal(), hexagonal()
  t_num, p_num, h_num = t_gen.next(), p_gen.next(), h_gen.next()
  count = 0
  while count < n:
    if t_num < p_num or t_num < h_num:
      t_num = t_gen.next()
    elif p_num < t_num or p_num < h_num:
      p_num = p_gen.next()
    elif h_num < t_num or h_num < p_num:
      h_num = h_gen.next()
    else:
      count += 1
      h_num = h_gen.next()

  return t_num


if __name__ == '__main__':
  try:
    print answer(int(sys.argv[1]))
  except:
    pass
