"""
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten
pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 −
22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of
D?
"""


def answer(limit=4000):
    pentagonals_l = [n*(3*n-1)//2 for n in range(1, limit)]
    pentagonals_s = set(pentagonals_l)
    for a_index, a in enumerate(pentagonals_l):
        for b_index in range(a_index, limit-1):
            b = pentagonals_l[b_index]
            if b+a in pentagonals_s and b-a in pentagonals_s:
                return b-a


if __name__ == '__main__':
    print(answer())